import XCTest
@testable import MeetingAgentCore

final class MeetingSummaryProviderTests: XCTestCase {
    func testSummaryInputRetainsTranscriptSourceMetadata() {
        let fallbackInput = MeetingSummaryInput(
            meetingName: "Launch Review",
            startedAt: Date(timeIntervalSince1970: 100),
            endedAt: Date(timeIntervalSince1970: 200),
            language: "en-US",
            meetingGoal: nil,
            transcript: Self.transcriptView(turns: []),
            transcriptSource: .fallback(reason: "Deepgram batch unavailable"),
            generatedAt: Date(timeIntervalSince1970: 300)
        )
        let defaultInput = MeetingSummaryInput(
            meetingName: "Launch Review",
            startedAt: Date(timeIntervalSince1970: 100),
            endedAt: Date(timeIntervalSince1970: 200),
            language: "en-US",
            meetingGoal: nil,
            transcript: Self.transcriptView(turns: []),
            generatedAt: Date(timeIntervalSince1970: 300)
        )

        XCTAssertEqual(fallbackInput.transcriptSource, .fallback(reason: "Deepgram batch unavailable"))
        XCTAssertEqual(defaultInput.transcriptSource, .live)
    }

    func testMarkdownRendererOmitsBlankSectionsAndRendersLists() {
        let summary = MeetingSummary(
            overview: " ",
            keyTopics: ["Launch", " "],
            decisions: [],
            actionItems: [],
            openQuestions: [],
            risks: [],
            followUps: ["Call legal"],
            language: nil,
            sourceSegmentIDs: [],
            generatedAt: Date(timeIntervalSince1970: 1_777_000_000),
            provider: "openrouter:openai/gpt-4.1-mini",
            status: .succeeded,
            failureReason: nil
        )

        let markdown = MeetingSummaryMarkdownRenderer.render(summary)

        XCTAssertFalse(markdown.contains("## Overview"))
        XCTAssertTrue(markdown.contains("## Key Topics\n\n- Launch"))
        XCTAssertTrue(markdown.contains("## Follow Ups\n\n- Call legal"))
    }

    func testMarkdownRendererIncludesTagsWithConfidenceAndRationale() {
        let summary = MeetingSummary(
            overview: "The team aligned on launch scope.",
            keyTopics: [],
            decisions: [],
            actionItems: [],
            openQuestions: [],
            risks: [],
            followUps: [],
            tags: [
                MeetingSummaryTag(
                    label: "结论较清晰",
                    rationale: "The team made a concrete launch decision.",
                    confidence: 0.84,
                    sourceSegmentIDs: ["segment-1", "segment-2"]
                )
            ],
            language: "en-US",
            sourceSegmentIDs: ["segment-1", "segment-2"],
            generatedAt: Date(timeIntervalSince1970: 1_777_000_000),
            provider: "openrouter:openai/gpt-4.1-mini",
            status: .succeeded,
            failureReason: nil
        )

        let markdown = MeetingSummaryMarkdownRenderer.render(summary)

        XCTAssertTrue(markdown.contains("## Tags"))
        XCTAssertTrue(markdown.contains("- 结论较清晰 (84%) - The team made a concrete launch decision."))
    }

    func testOpenRouterProviderBuildsRequestAndParsesSummary() async throws {
        let client = RecordingOpenRouterChatClient(responseContent: """
        {
          "overview": "The team aligned on launch scope.",
          "autoGeneratedTitle": "Launch Scope Alignment",
          "keyTopics": ["Launch"],
          "tags": [
            {
              "label": "市场进入策略讨论",
              "rationale": "The discussion focused on launch scope and legal risk.",
              "confidence": 0.84,
              "sourceSegmentIDs": ["segment-1", "segment-2"]
            }
          ],
          "decisions": [
            {
              "description": "Approved the launch date.",
              "participants": ["Alex"],
              "sourceSegmentIDs": ["segment-1"],
              "confidence": 0.82
            }
          ],
          "actionItems": [
            {
              "description": "Alex will follow up with legal.",
              "owner": "Alex",
              "dueDate": null,
              "sourceSegmentIDs": ["segment-2"],
              "confidence": 0.76
            }
          ],
          "openQuestions": ["Can support staff the launch?"],
          "risks": ["Legal review may delay launch."],
          "followUps": ["Alex will follow up with legal."]
        }
        """)
        let provider = OpenRouterMeetingSummaryProvider(
            configuration: OpenRouterChatConfiguration(apiKey: "test-key", model: "openai/gpt-4.1-mini"),
            client: client
        )

        let summary = try await provider.generateSummary(
            input: MeetingSummaryInput(
                meetingName: "Launch Review",
                startedAt: Date(timeIntervalSince1970: 1_777_000_000),
                endedAt: Date(timeIntervalSince1970: 1_777_000_600),
                language: "en-US",
                meetingGoal: nil,
                transcript: Self.transcriptView(turns: [
                    Self.turn(id: "segment-1", text: "We decided to launch on May 1.", sourceIDs: ["segment-1"]),
                    Self.turn(id: "segment-2", text: "Alex will follow up with legal.", sourceIDs: ["segment-2"])
                ]),
                generatedAt: Date(timeIntervalSince1970: 1_777_000_700)
            )
        )

        XCTAssertEqual(summary.status, .succeeded)
        XCTAssertEqual(summary.autoGeneratedTitle, "Launch Scope Alignment")
        XCTAssertEqual(summary.provider, "openrouter:openai/gpt-4.1-mini")
        XCTAssertEqual(summary.language, "en-US")
        XCTAssertEqual(summary.generatedAt, Date(timeIntervalSince1970: 1_777_000_700))
        XCTAssertEqual(summary.sourceSegmentIDs, ["segment-1", "segment-2"])
        XCTAssertEqual(summary.overview, "The team aligned on launch scope.")
        XCTAssertEqual(summary.tags.first?.label, "市场进入策略讨论")
        XCTAssertEqual(summary.tags.first?.rationale, "The discussion focused on launch scope and legal risk.")
        XCTAssertEqual(summary.tags.first?.confidence, 0.84)
        XCTAssertEqual(summary.tags.first?.sourceSegmentIDs, ["segment-1", "segment-2"])
        XCTAssertEqual(summary.decisions.first?.description, "Approved the launch date.")
        XCTAssertEqual(summary.decisions.first?.sourceSegmentIDs, ["segment-1"])
        XCTAssertEqual(summary.actionItems.first?.owner, "Alex")
        XCTAssertEqual(client.requests.first?.apiKey, "test-key")
        XCTAssertEqual(client.requests.first?.model, "openai/gpt-4.1-mini")
        XCTAssertEqual(client.requests.first?.responseFormat?.type, "json_object")
        XCTAssertEqual(client.requests.first?.messages.first?.role, "system")
        XCTAssertTrue(client.requests.first?.messages.first?.content.contains("autoGeneratedTitle") == true)
        XCTAssertTrue(client.requests.first?.messages.first?.content.contains("tags") == true)
        XCTAssertTrue(client.requests.first?.messages.first?.content.contains("2-4") == true)
        XCTAssertTrue(client.requests.first?.messages.last?.content.contains("segment-1") == true)
        XCTAssertTrue(client.requests.first?.messages.last?.content.contains("Transcript source: live") == true)
    }

    func testOpenRouterSummaryPromptUsesConsumptionTurnsWithSourceEvidence() async throws {
        let client = RecordingOpenRouterChatClient(responseContent: """
        {
          "overview": "团队确认负责人。",
          "keyTopics": [],
          "decisions": [],
          "actionItems": [],
          "openQuestions": [],
          "risks": [],
          "followUps": []
        }
        """)
        let provider = OpenRouterMeetingSummaryProvider(
            configuration: OpenRouterChatConfiguration(apiKey: "test-key", model: "openai/gpt-4.1-mini"),
            client: client
        )

        _ = try await provider.generateSummary(
            input: MeetingSummaryInput(
                meetingName: "Launch Review",
                startedAt: Date(timeIntervalSince1970: 1_777_000_000),
                endedAt: nil,
                language: "zh-CN",
                meetingGoal: nil,
                transcript: Self.transcriptView(turns: [
                    Self.turn(
                        id: "turn-1",
                        speakerLabel: "Allan",
                        text: "我们确认负责人。",
                        startTimeSeconds: 12,
                        endTimeSeconds: 25,
                        sourceIDs: ["utt-1"]
                    )
                ]),
                generatedAt: Date(timeIntervalSince1970: 1_777_000_100)
            )
        )

        let prompt = try XCTUnwrap(client.requests.first?.messages.last?.content)
        XCTAssertTrue(prompt.contains("[00:00:12-00:00:25] Allan"))
        XCTAssertTrue(prompt.contains("我们确认负责人。"))
        XCTAssertTrue(prompt.contains("source: utt-1"))
    }

    func testOpenRouterProviderFallsBackToLocalGeneratedTitleWhenPayloadOmitsTitle() async throws {
        let client = RecordingOpenRouterChatClient(responseContent: """
        {
          "overview": "The team aligned on renewal pricing.",
          "keyTopics": [],
          "decisions": [],
          "actionItems": [],
          "openQuestions": [],
          "risks": [],
          "followUps": []
        }
        """)
        let provider = OpenRouterMeetingSummaryProvider(
            configuration: OpenRouterChatConfiguration(apiKey: "test-key", model: "openai/gpt-4.1-mini"),
            client: client
        )

        let summary = try await provider.generateSummary(
            input: MeetingSummaryInput(
                meetingName: "Google Chrome",
                startedAt: Date(timeIntervalSince1970: 1_777_000_000),
                endedAt: Date(timeIntervalSince1970: 1_777_000_600),
                language: "en-US",
                meetingGoal: nil,
                transcript: Self.transcriptView(turns: [
                    Self.turn(id: "segment-1", text: "We agreed to update renewal pricing next week.", sourceIDs: ["segment-1"])
                ]),
                generatedAt: Date(timeIntervalSince1970: 1_777_000_700)
            )
        )

        XCTAssertEqual(summary.status, .succeeded)
        XCTAssertEqual(summary.autoGeneratedTitle, "Renewal pricing")
    }

    func testOpenRouterProviderRequestsSummaryInTargetLanguage() async throws {
        let client = RecordingOpenRouterChatClient(responseContent: """
        {
          "overview": "团队确认了发布范围。",
          "autoGeneratedTitle": "发布范围确认",
          "keyTopics": ["发布"],
          "decisions": [],
          "actionItems": [],
          "openQuestions": [],
          "risks": [],
          "followUps": []
        }
        """)
        let provider = OpenRouterMeetingSummaryProvider(
            configuration: OpenRouterChatConfiguration(apiKey: "test-key", model: "openai/gpt-4.1-mini"),
            client: client
        )

        _ = try await provider.generateSummary(
            input: MeetingSummaryInput(
                meetingName: "Launch Review",
                startedAt: Date(timeIntervalSince1970: 1_777_000_000),
                endedAt: nil,
                language: "en-US",
                targetLanguage: "zh-CN",
                meetingGoal: nil,
                transcript: Self.transcriptView(turns: [
                    Self.turn(id: "segment-1", text: "We decided to launch on May 1.", sourceIDs: ["segment-1"])
                ]),
                generatedAt: Date(timeIntervalSince1970: 1_777_000_100)
            )
        )

        let prompt = try XCTUnwrap(client.requests.first?.messages.last?.content)
        XCTAssertTrue(prompt.contains("Transcript language: en-US"))
        XCTAssertTrue(prompt.contains("Summary target language: zh-CN"))
        XCTAssertTrue(prompt.contains("Write every generated JSON string value in the summary target language."))
    }

    func testOpenRouterSummaryPromptIncludesTranscriptQualityContext() async throws {
        let client = RecordingOpenRouterChatClient(responseContent: """
        {
          "overview": "Fallback transcript summarized.",
          "keyTopics": [],
          "decisions": [],
          "actionItems": [],
          "openQuestions": [],
          "risks": [],
          "followUps": []
        }
        """)
        let provider = OpenRouterMeetingSummaryProvider(
            configuration: OpenRouterChatConfiguration(apiKey: "test-key", model: "openai/gpt-4.1-mini"),
            client: client
        )

        _ = try await provider.generateSummary(
            input: MeetingSummaryInput(
                meetingName: "Launch Review",
                startedAt: Date(timeIntervalSince1970: 1_777_000_000),
                endedAt: nil,
                language: "en-US",
                meetingGoal: nil,
                transcript: Self.transcriptView(
                    turns: [
                        Self.turn(id: "segment-1", text: "We decided to launch.", sourceIDs: ["segment-1"])
                    ],
                    quality: TranscriptConsumptionQuality(
                        source: .refinementFailed,
                        fallbackReason: "Transcript refinement failed: timeout",
                        finalTurnCount: 1,
                        draftTurnCount: 2,
                        unknownSpeakerTurnCount: 3,
                        emptyFinalTurnCount: 4
                    )
                ),
                generatedAt: Date(timeIntervalSince1970: 1_777_000_100)
            )
        )

        let prompt = try XCTUnwrap(client.requests.first?.messages.last?.content)
        XCTAssertTrue(prompt.contains("Transcript quality source: refinementFailed"))
        XCTAssertTrue(prompt.contains("finalTurns=1, draftTurns=2, unknownSpeakerTurns=3, emptyFinalTurns=4"))
        XCTAssertTrue(prompt.contains("Transcript fallback reason: Transcript refinement failed: timeout"))
    }

    func testOpenRouterProviderFailsWhenConfigurationIsMissing() async throws {
        let provider = OpenRouterMeetingSummaryProvider(
            configuration: .unavailable("OpenRouter API key is not configured"),
            client: RecordingOpenRouterChatClient(responseContent: "{}")
        )

        let summary = try await provider.generateSummary(
            input: MeetingSummaryInput(
                meetingName: "Launch Review",
                startedAt: Date(timeIntervalSince1970: 1_777_000_000),
                endedAt: nil,
                language: "en-US",
                meetingGoal: nil,
                transcript: Self.transcriptView(turns: [
                    Self.turn(id: "segment-1", text: "We decided to launch on May 1.", sourceIDs: ["segment-1"])
                ]),
                generatedAt: Date(timeIntervalSince1970: 1_777_000_100)
            )
        )

        XCTAssertEqual(summary.status, .failed)
        XCTAssertNil(summary.autoGeneratedTitle)
        XCTAssertEqual(summary.provider, "openrouter")
        XCTAssertEqual(summary.failureReason, "OpenRouter API key is not configured")
        XCTAssertEqual(summary.sourceSegmentIDs, ["segment-1"])
        XCTAssertEqual(summary.tags, [])
    }

    func testSummaryWriterWritesJSONAndMarkdownTogether() throws {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("summary-writer-\(UUID().uuidString)", isDirectory: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let jsonURL = directory.appendingPathComponent("summary.json")
        let markdownURL = directory.appendingPathComponent("summary.md")
        let summary = MeetingSummary(
            overview: "The team aligned on launch scope.",
            keyTopics: ["Launch"],
            decisions: [
                MeetingDecision(
                    description: "Approved the launch date.",
                    participants: ["User A"],
                    sourceSegmentIDs: ["segment-1"],
                    confidence: 0.8
                )
            ],
            actionItems: [
                MeetingActionItem(
                    description: "Follow up with legal.",
                    owner: "User B",
                    dueDate: nil,
                    sourceSegmentIDs: ["segment-2"],
                    confidence: 0.7
                )
            ],
            openQuestions: ["Can support staff the launch?"],
            risks: ["Legal review may delay launch."],
            followUps: ["Schedule launch review."],
            language: "en-US",
            sourceSegmentIDs: ["segment-1", "segment-2"],
            generatedAt: Date(timeIntervalSince1970: 1_777_000_000),
            provider: "openrouter:openai/gpt-4.1-mini",
            status: .succeeded,
            failureReason: nil
        )

        try MeetingSummaryWriter.write(summary, jsonURL: jsonURL, markdownURL: markdownURL)

        XCTAssertEqual(try MeetingSummaryWriter.read(from: jsonURL), summary)
        let markdown = try String(contentsOf: markdownURL, encoding: .utf8)
        XCTAssertTrue(markdown.contains("# Meeting Summary"))
        XCTAssertTrue(markdown.contains("The team aligned on launch scope."))
        XCTAssertTrue(markdown.contains("Approved the launch date."))
        XCTAssertTrue(markdown.contains("Follow up with legal."))
        XCTAssertTrue(markdown.contains("Can support staff the launch?"))
    }

    func testMarkdownRendererIncludesFailureReason() {
        let summary = MeetingSummary(
            overview: "",
            keyTopics: [],
            decisions: [],
            actionItems: [],
            openQuestions: [],
            risks: [],
            followUps: [],
            language: "en-US",
            sourceSegmentIDs: [],
            generatedAt: Date(timeIntervalSince1970: 1_777_000_000),
            provider: "openrouter:openai/gpt-4.1-mini",
            status: .failed,
            failureReason: "No transcript was available."
        )

        let markdown = MeetingSummaryMarkdownRenderer.render(summary)

        XCTAssertTrue(markdown.contains("Status: failed"))
        XCTAssertTrue(markdown.contains("No transcript was available."))
    }

    private static func transcriptView(
        turns: [TranscriptConsumptionTurn],
        language: String = "en-US",
        quality: TranscriptConsumptionQuality? = nil
    ) -> TranscriptConsumptionView {
        TranscriptConsumptionView(
            meetingID: UUID(uuidString: "00000000-0000-0000-0000-000000000001")!,
            language: language,
            provider: CaptionProviderInfo(id: "test", locale: language),
            finalTurns: turns,
            quality: quality ?? TranscriptConsumptionQuality(finalTurnCount: turns.count)
        )
    }

    private static func turn(
        id: String,
        speakerLabel: String = "Alex",
        text: String,
        startTimeSeconds: Double? = nil,
        endTimeSeconds: Double? = nil,
        sourceIDs: [String]
    ) -> TranscriptConsumptionTurn {
        TranscriptConsumptionTurn(
            turnID: id,
            speakerID: speakerLabel.lowercased(),
            speakerLabel: speakerLabel,
            sections: [
                TranscriptConsumptionSection(
                    id: "\(id)-section",
                    text: text,
                    startTimeSeconds: startTimeSeconds,
                    endTimeSeconds: endTimeSeconds,
                    sourceIDs: sourceIDs
                )
            ],
            startTimeSeconds: startTimeSeconds,
            endTimeSeconds: endTimeSeconds,
            sourceIDs: sourceIDs
        )
    }
}

private final class RecordingOpenRouterChatClient: OpenRouterChatClient {
    struct Request: Equatable {
        let apiKey: String
        let model: String
        let messages: [OpenRouterChatMessage]
        let responseFormat: OpenRouterResponseFormat?
    }

    private(set) var requests: [Request] = []
    private let responseContent: String

    init(responseContent: String) {
        self.responseContent = responseContent
    }

    func complete(
        configuration: OpenRouterChatConfiguration,
        messages: [OpenRouterChatMessage],
        responseFormat: OpenRouterResponseFormat?
    ) async throws -> String {
        requests.append(Request(
            apiKey: configuration.apiKey,
            model: configuration.model,
            messages: messages,
            responseFormat: responseFormat
        ))
        return responseContent
    }
}
