import XCTest
@testable import MeetingAgentCore

final class MeetingSummaryTests: XCTestCase {
    func testMeetingSummaryEncodesAndDecodes() throws {
        let summary = MeetingSummary(
            autoGeneratedTitle: "Launch Review",
            overview: "The team aligned on launch scope.",
            keyTopics: ["Launch"],
            decisions: [
                MeetingDecision(
                    description: "Approved the launch date.",
                    participants: ["User A"],
                    sourceSegmentIDs: ["segment-1"],
                    confidence: 0.8
                )
            ],
            actionItems: [
                MeetingActionItem(
                    description: "Follow up with legal.",
                    owner: "User B",
                    dueDate: nil,
                    sourceSegmentIDs: ["segment-2"],
                    confidence: 0.7
                )
            ],
            openQuestions: ["Can support staff the launch?"],
            risks: ["Legal review may delay launch."],
            followUps: ["Schedule launch review."],
            language: "en-US",
            sourceSegmentIDs: ["segment-1", "segment-2"],
            generatedAt: Date(timeIntervalSince1970: 1_777_000_000),
            provider: "openrouter:openai/gpt-4.1-mini",
            status: .succeeded,
            failureReason: nil
        )

        let data = try JSONEncoder.meetingAgent.encode(summary)
        let decoded = try JSONDecoder.meetingAgent.decode(MeetingSummary.self, from: data)

        XCTAssertEqual(decoded, summary)
    }

    func testMeetingSummaryDecodesLegacyJSONWithoutGeneratedTitle() throws {
        let json = """
        {
          "overview": "The team aligned on launch scope.",
          "keyTopics": ["Launch"],
          "decisions": [],
          "actionItems": [],
          "openQuestions": [],
          "risks": [],
          "followUps": [],
          "language": "en-US",
          "sourceSegmentIDs": ["segment-1"],
          "generatedAt": "2026-04-29T01:00:00Z",
          "provider": "openrouter:openai/gpt-4.1-mini",
          "status": "succeeded",
          "failureReason": null
        }
        """

        let decoded = try JSONDecoder.meetingAgent.decode(MeetingSummary.self, from: Data(json.utf8))

        XCTAssertNil(decoded.autoGeneratedTitle)
        XCTAssertEqual(decoded.overview, "The team aligned on launch scope.")
    }

    func testMeetingSummaryNormalizesBlankGeneratedTitle() {
        let summary = MeetingSummary(
            autoGeneratedTitle: " \n ",
            overview: "The team aligned on launch scope.",
            keyTopics: [],
            decisions: [],
            actionItems: [],
            openQuestions: [],
            risks: [],
            followUps: [],
            language: "en-US",
            sourceSegmentIDs: [],
            generatedAt: Date(timeIntervalSince1970: 1_777_000_000),
            provider: "test",
            status: .succeeded,
            failureReason: nil
        )

        XCTAssertNil(summary.autoGeneratedTitle)
    }

    func testSummaryTitleGeneratorUsesTranscriptSegmentWhenOverviewIsGeneric() {
        let title = MeetingSummaryTitleGenerator.title(
            meetingName: "Google Meet",
            keyTopics: [],
            overview: "Meeting detected",
            segments: [
                TranscriptSegment(
                    id: "segment-1",
                    text: "the team aligned on japan launch staffing risks before the cutoff date",
                    sourceProvider: "test"
                )
            ]
        )

        XCTAssertEqual(title, "Japan launch staffing risks before the cutoff date")
    }

    func testSummaryTitleGeneratorFallsBackToNonGenericMeetingName() {
        XCTAssertEqual(
            MeetingSummaryTitleGenerator.title(
                meetingName: "  Launch Review!  ",
                keyTopics: [],
                overview: "  ",
                segments: []
            ),
            "Launch Review"
        )
        XCTAssertNil(
            MeetingSummaryTitleGenerator.title(
                meetingName: "Zoom",
                keyTopics: [],
                overview: "",
                segments: []
            )
        )
    }
}
