import Foundation

public struct KarpathyWikiConnector: KnowledgeConnector {
    public let id = "karpathy-wiki"
    public let displayName = "Karpathy Wiki"

    private let fileManager: FileManager
    private let writer: MeetingKnowledgePackageWriter
    private let now: () -> Date

    public init(
        fileManager: FileManager = .default,
        writer: MeetingKnowledgePackageWriter = MeetingKnowledgePackageWriter(),
        now: @escaping () -> Date = Date.init
    ) {
        self.fileManager = fileManager
        self.writer = writer
        self.now = now
    }

    public func validate(configuration: KnowledgeConnectorConfiguration) async -> KnowledgeConnectorValidation {
        guard configuration.kind == .karpathyWiki else {
            return .unavailable("Configuration is not for Karpathy Wiki.")
        }
        guard let rootURL = configuration.rootURL else {
            return .unavailable("Karpathy Wiki root is not configured.")
        }

        var isDirectory: ObjCBool = false
        if fileManager.fileExists(atPath: rootURL.path, isDirectory: &isDirectory), !isDirectory.boolValue {
            return .unavailable("Karpathy Wiki root is a file.")
        }

        let parent = rootURL.deletingLastPathComponent()
        guard fileManager.isWritableFile(atPath: parent.path) || fileManager.isWritableFile(atPath: rootURL.path) else {
            return .unavailable("Karpathy Wiki root is not writable.")
        }

        return .available("Karpathy Wiki root is available.")
    }

    public func sync(package: MeetingKnowledgePackage, configuration: KnowledgeConnectorConfiguration) async throws -> KnowledgeSyncResult {
        guard configuration.kind == .karpathyWiki else {
            throw KnowledgeConnectorError.invalidConnectorKind(configuration.kind)
        }
        guard let rootURL = configuration.rootURL else {
            throw KnowledgeConnectorError.missingRoot
        }

        let destination = packageURL(for: package, rootURL: rootURL)
        if fileManager.fileExists(atPath: destination.path) {
            throw KnowledgeConnectorError.destinationAlreadyExists(destination.path)
        }

        let result = try writer.write(package, to: destination)
        return KnowledgeSyncResult(
            connectorID: id,
            status: .succeeded,
            destinationDescription: destination.path,
            filesWritten: result.filesWritten,
            commandOutput: nil,
            syncedAt: now()
        )
    }

    public func packageURL(for package: MeetingKnowledgePackage, rootURL: URL) -> URL {
        rootURL
            .appendingPathComponent("raw", isDirectory: true)
            .appendingPathComponent("meetings", isDirectory: true)
            .appendingPathComponent(Self.slug(for: package), isDirectory: true)
    }

    public static func slug(for package: MeetingKnowledgePackage) -> String {
        let date = String(ISO8601DateFormatter().string(from: package.record.startedAt).prefix(10))
        let title = package.summary?.autoGeneratedTitle ?? package.record.name
        let slugTitle = slugify(title)
        if slugTitle.isEmpty {
            return "\(date)-\(package.record.id.uuidString.prefix(8).lowercased())"
        }
        return "\(date)-\(slugTitle)"
    }

    private static func slugify(_ value: String) -> String {
        let lowercased = value.lowercased()
        let allowed = CharacterSet.alphanumerics
        var scalars: [String] = []
        var previousWasDash = false

        for scalar in lowercased.unicodeScalars {
            if allowed.contains(scalar) {
                scalars.append(String(scalar))
                previousWasDash = false
            } else if !previousWasDash {
                scalars.append("-")
                previousWasDash = true
            }
        }

        return scalars
            .joined()
            .trimmingCharacters(in: CharacterSet(charactersIn: "-"))
    }
}
