import Foundation

public enum MeetingSummaryStatus: String, Codable, Equatable {
    case succeeded
    case failed
}

public struct MeetingActionItem: Codable, Equatable {
    public let description: String
    public let owner: String?
    public let dueDate: String?
    public let sourceSegmentIDs: [String]
    public let confidence: Double

    public init(
        description: String,
        owner: String?,
        dueDate: String?,
        sourceSegmentIDs: [String],
        confidence: Double
    ) {
        self.description = description
        self.owner = owner
        self.dueDate = dueDate
        self.sourceSegmentIDs = sourceSegmentIDs
        self.confidence = confidence
    }
}

public struct MeetingDecision: Codable, Equatable {
    public let description: String
    public let participants: [String]
    public let sourceSegmentIDs: [String]
    public let confidence: Double

    public init(
        description: String,
        participants: [String],
        sourceSegmentIDs: [String],
        confidence: Double
    ) {
        self.description = description
        self.participants = participants
        self.sourceSegmentIDs = sourceSegmentIDs
        self.confidence = confidence
    }
}

public struct MeetingSummary: Codable, Equatable {
    public let autoGeneratedTitle: String?
    public let overview: String
    public let keyTopics: [String]
    public let decisions: [MeetingDecision]
    public let actionItems: [MeetingActionItem]
    public let openQuestions: [String]
    public let risks: [String]
    public let followUps: [String]
    public let language: String?
    public let sourceSegmentIDs: [String]
    public let generatedAt: Date
    public let provider: String
    public let status: MeetingSummaryStatus
    public let failureReason: String?

    public init(
        autoGeneratedTitle: String? = nil,
        overview: String,
        keyTopics: [String],
        decisions: [MeetingDecision],
        actionItems: [MeetingActionItem],
        openQuestions: [String],
        risks: [String],
        followUps: [String],
        language: String?,
        sourceSegmentIDs: [String],
        generatedAt: Date,
        provider: String,
        status: MeetingSummaryStatus,
        failureReason: String?
    ) {
        self.autoGeneratedTitle = Self.normalizedOptionalTitle(autoGeneratedTitle)
        self.overview = overview
        self.keyTopics = keyTopics
        self.decisions = decisions
        self.actionItems = actionItems
        self.openQuestions = openQuestions
        self.risks = risks
        self.followUps = followUps
        self.language = language
        self.sourceSegmentIDs = sourceSegmentIDs
        self.generatedAt = generatedAt
        self.provider = provider
        self.status = status
        self.failureReason = failureReason
    }

    private enum CodingKeys: String, CodingKey {
        case autoGeneratedTitle
        case overview
        case keyTopics
        case decisions
        case actionItems
        case openQuestions
        case risks
        case followUps
        case language
        case sourceSegmentIDs
        case generatedAt
        case provider
        case status
        case failureReason
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        autoGeneratedTitle = Self.normalizedOptionalTitle(try container.decodeIfPresent(String.self, forKey: .autoGeneratedTitle))
        overview = try container.decode(String.self, forKey: .overview)
        keyTopics = try container.decode([String].self, forKey: .keyTopics)
        decisions = try container.decode([MeetingDecision].self, forKey: .decisions)
        actionItems = try container.decode([MeetingActionItem].self, forKey: .actionItems)
        openQuestions = try container.decode([String].self, forKey: .openQuestions)
        risks = try container.decode([String].self, forKey: .risks)
        followUps = try container.decode([String].self, forKey: .followUps)
        language = try container.decodeIfPresent(String.self, forKey: .language)
        sourceSegmentIDs = try container.decode([String].self, forKey: .sourceSegmentIDs)
        generatedAt = try container.decode(Date.self, forKey: .generatedAt)
        provider = try container.decode(String.self, forKey: .provider)
        status = try container.decode(MeetingSummaryStatus.self, forKey: .status)
        failureReason = try container.decodeIfPresent(String.self, forKey: .failureReason)
    }

    private static func normalizedOptionalTitle(_ title: String?) -> String? {
        guard let title else { return nil }
        let normalized = title
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return normalized.isEmpty ? nil : normalized
    }
}

enum MeetingSummaryTitleGenerator {
    static func title(
        meetingName: String,
        keyTopics: [String],
        overview: String,
        segments: [TranscriptSegment]
    ) -> String? {
        let candidates = [overview] + segments.map(\.text) + keyTopics
        for candidate in candidates {
            guard let normalized = normalizedTitle(candidate),
                  !isGenericMeetingName(normalized),
                  !normalized.isEmpty
            else { continue }
            return normalized
        }
        return normalizedTitle(meetingName).flatMap { isGenericMeetingName($0) ? nil : $0 }
    }

    static func isGenericMeetingName(_ name: String) -> Bool {
        let normalized = normalizedComparableName(name)
        guard !normalized.isEmpty else { return true }
        if normalized.hasPrefix("meeting detected") { return true }
        let genericNames: Set<String> = [
            "new meeting",
            "meeting",
            "google chrome",
            "chrome",
            "safari",
            "microsoft edge",
            "firefox",
            "arc",
            "zoom",
            "zoom.us",
            "google meet",
            "meet",
            "microsoft teams",
            "teams",
            "slack",
            "feishu",
            "lark"
        ]
        return genericNames.contains(normalized)
    }

    private static func normalizedTitle(_ text: String) -> String? {
        let compact = text
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !compact.isEmpty else { return nil }

        let firstSentence = compact
            .components(separatedBy: CharacterSet(charactersIn: ".!?。！？"))
            .first?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? compact
        let stripped = stripLeadingSummaryPhrase(firstSentence)
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: ":：- "))
        guard !stripped.isEmpty else { return nil }

        let words = stripped.split(separator: " ")
        if words.count > 8 {
            return capitalizedLeadingCharacter(words.prefix(8).joined(separator: " "))
        }
        return capitalizedLeadingCharacter(stripped)
    }

    private static func stripLeadingSummaryPhrase(_ text: String) -> String {
        let lowercased = text.lowercased()
        let prefixes = [
            "the meeting focused on ",
            "this meeting focused on ",
            "the team aligned on ",
            "we decided to ",
            "we agreed to ",
            "discussed ",
            "discussion about "
        ]
        for prefix in prefixes where lowercased.hasPrefix(prefix) {
            return String(text.dropFirst(prefix.count))
        }
        return text
    }

    private static func capitalizedLeadingCharacter(_ text: String) -> String {
        guard let first = text.first, first.isLowercase else { return text }
        return first.uppercased() + text.dropFirst()
    }

    private static func normalizedComparableName(_ name: String) -> String {
        name
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
            .trimmingCharacters(in: .punctuationCharacters)
            .lowercased()
    }
}

public struct MeetingSummaryInput: Equatable {
    public let meetingName: String
    public let startedAt: Date
    public let endedAt: Date?
    public let language: String?
    public let meetingGoal: String?
    public let segments: [TranscriptSegment]
    public let generatedAt: Date

    public init(
        meetingName: String,
        startedAt: Date,
        endedAt: Date?,
        language: String?,
        meetingGoal: String?,
        segments: [TranscriptSegment],
        generatedAt: Date = Date()
    ) {
        self.meetingName = meetingName
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.language = language
        self.meetingGoal = meetingGoal
        self.segments = segments
        self.generatedAt = generatedAt
    }
}

public protocol MeetingSummaryProvider {
    var providerName: String { get }
    func generateSummary(input: MeetingSummaryInput) async throws -> MeetingSummary
}

public struct ExtractiveMeetingSummaryProvider: MeetingSummaryProvider {
    public let providerName = "extractive-local"

    public init() {}

    public func generateSummary(input: MeetingSummaryInput) async throws -> MeetingSummary {
        let usableSegments = input.segments.compactMap(SummarySegment.init(segment:))
        guard !usableSegments.isEmpty else {
            return MeetingSummary(
                autoGeneratedTitle: nil,
                overview: "",
                keyTopics: [],
                decisions: [],
                actionItems: [],
                openQuestions: [],
                risks: [],
                followUps: [],
                language: input.language,
                sourceSegmentIDs: [],
                generatedAt: input.generatedAt,
                provider: providerName,
                status: .failed,
                failureReason: "No usable transcript segments were available for summary generation."
            )
        }

        let decisions = usableSegments
            .filter { containsAny($0.lowercasedText, keywords: Self.decisionKeywords) }
            .map {
                MeetingDecision(
                    description: $0.text,
                    participants: $0.speakerLabel.map { [$0] } ?? [],
                    sourceSegmentIDs: [$0.id],
                    confidence: 0.65
                )
            }

        let actionItems = usableSegments
            .filter { containsAny($0.lowercasedText, keywords: Self.actionKeywords) }
            .map {
                MeetingActionItem(
                    description: $0.text,
                    owner: inferredOwner(from: $0.text),
                    dueDate: nil,
                    sourceSegmentIDs: [$0.id],
                    confidence: 0.6
                )
            }

        let openQuestions = usableSegments
            .filter { isQuestion($0.text) }
            .map(\.text)

        let risks = usableSegments
            .filter { containsAny($0.lowercasedText, keywords: Self.riskKeywords) }
            .map(\.text)

        let overview = overview(from: usableSegments, meetingGoal: input.meetingGoal)
        let topics = keyTopics(from: usableSegments, meetingName: input.meetingName)
        return MeetingSummary(
            autoGeneratedTitle: MeetingSummaryTitleGenerator.title(
                meetingName: input.meetingName,
                keyTopics: topics,
                overview: overview,
                segments: input.segments
            ),
            overview: overview,
            keyTopics: topics,
            decisions: decisions,
            actionItems: actionItems,
            openQuestions: openQuestions,
            risks: risks,
            followUps: actionItems.map(\.description),
            language: input.language ?? usableSegments.compactMap(\.language).first,
            sourceSegmentIDs: usableSegments.map(\.id),
            generatedAt: input.generatedAt,
            provider: providerName,
            status: .succeeded,
            failureReason: nil
        )
    }

    private static let decisionKeywords = ["decided", "decision", "approved", "agreed"]
    private static let actionKeywords = ["action item", "todo", "follow up", "will", "need to"]
    private static let questionKeywords = ["can ", "could ", "should ", "what ", "when ", "where ", "who ", "why ", "how "]
    private static let riskKeywords = ["risk", "blocked", "concern", "delay", "issue"]

    private func containsAny(_ text: String, keywords: [String]) -> Bool {
        keywords.contains { text.contains($0) }
    }

    private func isQuestion(_ text: String) -> Bool {
        let lowercased = text.lowercased()
        return text.hasSuffix("?") || containsAny(lowercased, keywords: Self.questionKeywords)
    }

    private func overview(from segments: [SummarySegment], meetingGoal: String?) -> String {
        if let meetingGoal, !meetingGoal.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return "The meeting focused on \(meetingGoal.trimmingCharacters(in: .whitespacesAndNewlines)). \(segments[0].text)"
        }
        return segments.prefix(2).map(\.text).joined(separator: " ")
    }

    private func keyTopics(from segments: [SummarySegment], meetingName: String) -> [String] {
        let name = meetingName.trimmingCharacters(in: .whitespacesAndNewlines)
        if !name.isEmpty {
            return [name]
        }
        return Array(
            Set(segments.flatMap { words(from: $0.text).filter { $0.count > 5 } })
        )
        .sorted()
        .prefix(3)
        .map { String($0) }
    }

    private func inferredOwner(from text: String) -> String? {
        let words = text.split(separator: " ")
        guard let first = words.first else { return nil }
        let candidate = String(first).trimmingCharacters(in: .punctuationCharacters)
        guard candidate.first?.isUppercase == true else { return nil }
        return candidate
    }

    private func words(from text: String) -> [String] {
        text.components(separatedBy: CharacterSet.alphanumerics.inverted)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }
}

public enum MeetingSummaryMarkdownRenderer {
    public static func render(_ summary: MeetingSummary) -> String {
        var lines: [String] = [
            "# Meeting Summary",
            "",
            "Status: \(summary.status.rawValue)",
            "Provider: \(summary.provider)",
            ""
        ]

        if let failureReason = summary.failureReason {
            lines.append("Failure reason: \(failureReason)")
            lines.append("")
        }

        appendSection("Overview", items: [summary.overview], to: &lines)
        appendSection("Key Topics", items: summary.keyTopics, to: &lines)
        appendSection("Decisions", items: summary.decisions.map(\.description), to: &lines)
        appendSection("Action Items", items: summary.actionItems.map(\.description), to: &lines)
        appendSection("Open Questions", items: summary.openQuestions, to: &lines)
        appendSection("Risks", items: summary.risks, to: &lines)
        appendSection("Follow Ups", items: summary.followUps, to: &lines)

        return lines.joined(separator: "\n") + "\n"
    }

    private static func appendSection(_ title: String, items: [String], to lines: inout [String]) {
        let visibleItems = items
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        guard !visibleItems.isEmpty else { return }
        lines.append("## \(title)")
        lines.append("")
        if visibleItems.count == 1, title == "Overview" {
            lines.append(visibleItems[0])
        } else {
            lines.append(contentsOf: visibleItems.map { "- \($0)" })
        }
        lines.append("")
    }
}

public enum MeetingSummaryWriter {
    public static func write(_ summary: MeetingSummary, jsonURL: URL, markdownURL: URL) throws {
        let data = try JSONEncoder.meetingAgent.encode(summary)
        try data.write(to: jsonURL, options: .atomic)
        try MeetingSummaryMarkdownRenderer.render(summary).write(to: markdownURL, atomically: true, encoding: .utf8)
    }

    public static func read(from url: URL) throws -> MeetingSummary {
        let data = try Data(contentsOf: url)
        return try JSONDecoder.meetingAgent.decode(MeetingSummary.self, from: data)
    }
}

private struct SummarySegment {
    let id: String
    let text: String
    let lowercasedText: String
    let speakerLabel: String?
    let language: String?

    init?(segment: TranscriptSegment) {
        let text = segment.text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty else { return nil }
        self.id = segment.id
        self.text = text
        self.lowercasedText = text.lowercased()
        self.speakerLabel = segment.speakerLabel
        self.language = segment.language
    }
}
