import Foundation

public enum MeetingSummaryStatus: String, Codable, Equatable {
    case succeeded
    case failed
}

public struct MeetingActionItem: Codable, Equatable {
    public let description: String
    public let owner: String?
    public let dueDate: String?
    public let sourceSegmentIDs: [String]
    public let confidence: Double

    public init(
        description: String,
        owner: String?,
        dueDate: String?,
        sourceSegmentIDs: [String],
        confidence: Double
    ) {
        self.description = description
        self.owner = owner
        self.dueDate = dueDate
        self.sourceSegmentIDs = sourceSegmentIDs
        self.confidence = confidence
    }
}

public struct MeetingDecision: Codable, Equatable {
    public let description: String
    public let participants: [String]
    public let sourceSegmentIDs: [String]
    public let confidence: Double

    public init(
        description: String,
        participants: [String],
        sourceSegmentIDs: [String],
        confidence: Double
    ) {
        self.description = description
        self.participants = participants
        self.sourceSegmentIDs = sourceSegmentIDs
        self.confidence = confidence
    }
}

public struct MeetingSummaryTag: Codable, Equatable {
    public let label: String
    public let rationale: String?
    public let confidence: Double
    public let sourceSegmentIDs: [String]

    public init(label: String, rationale: String?, confidence: Double, sourceSegmentIDs: [String]) {
        self.label = label
        self.rationale = rationale
        self.confidence = confidence
        self.sourceSegmentIDs = sourceSegmentIDs
    }
}

public struct MeetingSummary: Codable, Equatable {
    public let autoGeneratedTitle: String?
    public let overview: String
    public let keyTopics: [String]
    public let decisions: [MeetingDecision]
    public let actionItems: [MeetingActionItem]
    public let openQuestions: [String]
    public let risks: [String]
    public let followUps: [String]
    public let tags: [MeetingSummaryTag]
    public let language: String?
    public let sourceSegmentIDs: [String]
    public let generatedAt: Date
    public let provider: String
    public let status: MeetingSummaryStatus
    public let failureReason: String?

    public init(
        autoGeneratedTitle: String? = nil,
        overview: String,
        keyTopics: [String],
        decisions: [MeetingDecision],
        actionItems: [MeetingActionItem],
        openQuestions: [String],
        risks: [String],
        followUps: [String],
        tags: [MeetingSummaryTag] = [],
        language: String?,
        sourceSegmentIDs: [String],
        generatedAt: Date,
        provider: String,
        status: MeetingSummaryStatus,
        failureReason: String?
    ) {
        self.autoGeneratedTitle = Self.normalizedOptionalTitle(autoGeneratedTitle)
        self.overview = overview
        self.keyTopics = keyTopics
        self.decisions = decisions
        self.actionItems = actionItems
        self.openQuestions = openQuestions
        self.risks = risks
        self.followUps = followUps
        self.tags = tags
        self.language = language
        self.sourceSegmentIDs = sourceSegmentIDs
        self.generatedAt = generatedAt
        self.provider = provider
        self.status = status
        self.failureReason = failureReason
    }

    private enum CodingKeys: String, CodingKey {
        case autoGeneratedTitle
        case overview
        case keyTopics
        case decisions
        case actionItems
        case openQuestions
        case risks
        case followUps
        case tags
        case language
        case sourceSegmentIDs
        case generatedAt
        case provider
        case status
        case failureReason
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        autoGeneratedTitle = Self.normalizedOptionalTitle(try container.decodeIfPresent(String.self, forKey: .autoGeneratedTitle))
        overview = try container.decode(String.self, forKey: .overview)
        keyTopics = try container.decode([String].self, forKey: .keyTopics)
        decisions = try container.decode([MeetingDecision].self, forKey: .decisions)
        actionItems = try container.decode([MeetingActionItem].self, forKey: .actionItems)
        openQuestions = try container.decode([String].self, forKey: .openQuestions)
        risks = try container.decode([String].self, forKey: .risks)
        followUps = try container.decode([String].self, forKey: .followUps)
        tags = try container.decodeIfPresent([MeetingSummaryTag].self, forKey: .tags) ?? []
        language = try container.decodeIfPresent(String.self, forKey: .language)
        sourceSegmentIDs = try container.decode([String].self, forKey: .sourceSegmentIDs)
        generatedAt = try container.decode(Date.self, forKey: .generatedAt)
        provider = try container.decode(String.self, forKey: .provider)
        status = try container.decode(MeetingSummaryStatus.self, forKey: .status)
        failureReason = try container.decodeIfPresent(String.self, forKey: .failureReason)
    }

    private static func normalizedOptionalTitle(_ title: String?) -> String? {
        guard let title else { return nil }
        let normalized = title
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        return normalized.isEmpty ? nil : normalized
    }
}

enum MeetingSummaryTitleGenerator {
    static func title(
        meetingName: String,
        keyTopics: [String],
        overview: String,
        segments: [TranscriptSegment]
    ) -> String? {
        title(
            meetingName: meetingName,
            keyTopics: keyTopics,
            overview: overview,
            transcriptTexts: segments.map(\.text)
        )
    }

    static func title(
        meetingName: String,
        keyTopics: [String],
        overview: String,
        transcriptTurns: [TranscriptConsumptionTurn]
    ) -> String? {
        title(
            meetingName: meetingName,
            keyTopics: keyTopics,
            overview: overview,
            transcriptTexts: transcriptTurns.map(\.text)
        )
    }

    private static func title(
        meetingName: String,
        keyTopics: [String],
        overview: String,
        transcriptTexts: [String]
    ) -> String? {
        let candidates = [overview] + transcriptTexts + keyTopics
        for candidate in candidates {
            guard let normalized = normalizedTitle(candidate),
                  !isGenericMeetingName(normalized),
                  !normalized.isEmpty
            else { continue }
            return normalized
        }
        return normalizedTitle(meetingName).flatMap { isGenericMeetingName($0) ? nil : $0 }
    }

    static func isGenericMeetingName(_ name: String) -> Bool {
        let normalized = normalizedComparableName(name)
        guard !normalized.isEmpty else { return true }
        if normalized.hasPrefix("meeting detected") { return true }
        let genericNames: Set<String> = [
            "new meeting",
            "meeting",
            "google chrome",
            "chrome",
            "safari",
            "microsoft edge",
            "firefox",
            "arc",
            "zoom",
            "zoom.us",
            "google meet",
            "meet",
            "microsoft teams",
            "teams",
            "slack",
            "feishu",
            "lark"
        ]
        return genericNames.contains(normalized)
    }

    private static func normalizedTitle(_ text: String) -> String? {
        let compact = text
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !compact.isEmpty else { return nil }

        let firstSentence = compact
            .components(separatedBy: CharacterSet(charactersIn: ".!?。！？"))
            .first?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? compact
        let stripped = stripLeadingSummaryPhrase(firstSentence)
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: ":：- "))
        guard !stripped.isEmpty else { return nil }

        let words = stripped.split(separator: " ")
        if words.count > 8 {
            return capitalizedLeadingCharacter(words.prefix(8).joined(separator: " "))
        }
        return capitalizedLeadingCharacter(stripped)
    }

    private static func stripLeadingSummaryPhrase(_ text: String) -> String {
        let lowercased = text.lowercased()
        let prefixes = [
            "the meeting focused on ",
            "this meeting focused on ",
            "the team aligned on ",
            "we decided to ",
            "we agreed to ",
            "discussed ",
            "discussion about "
        ]
        for prefix in prefixes where lowercased.hasPrefix(prefix) {
            return String(text.dropFirst(prefix.count))
        }
        return text
    }

    private static func capitalizedLeadingCharacter(_ text: String) -> String {
        guard let first = text.first, first.isLowercase else { return text }
        return first.uppercased() + text.dropFirst()
    }

    private static func normalizedComparableName(_ name: String) -> String {
        name
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
            .trimmingCharacters(in: .punctuationCharacters)
            .lowercased()
    }
}

public struct MeetingSummaryInput: Equatable {
    public let meetingName: String
    public let startedAt: Date
    public let endedAt: Date?
    public let language: String?
    public let targetLanguage: String?
    public let meetingGoal: String?
    public let transcript: TranscriptConsumptionView
    public let generatedAt: Date

    public init(
        meetingName: String,
        startedAt: Date,
        endedAt: Date?,
        language: String?,
        targetLanguage: String? = nil,
        meetingGoal: String?,
        transcript: TranscriptConsumptionView,
        generatedAt: Date = Date()
    ) {
        self.meetingName = meetingName
        self.startedAt = startedAt
        self.endedAt = endedAt
        self.language = language
        self.targetLanguage = targetLanguage
        self.meetingGoal = meetingGoal
        self.transcript = transcript
        self.generatedAt = generatedAt
    }
}

public protocol MeetingSummaryProvider {
    var providerName: String { get }
    func generateSummary(input: MeetingSummaryInput) async throws -> MeetingSummary
}

public enum MeetingSummaryMarkdownRenderer {
    public static func render(_ summary: MeetingSummary) -> String {
        var lines: [String] = [
            "# Meeting Summary",
            "",
            "Status: \(summary.status.rawValue)",
            "Provider: \(summary.provider)",
            ""
        ]

        if let failureReason = summary.failureReason {
            lines.append("Failure reason: \(failureReason)")
            lines.append("")
        }

        appendSection("Overview", items: [summary.overview], to: &lines)
        appendSection("Key Topics", items: summary.keyTopics, to: &lines)
        appendTags(summary.tags, to: &lines)
        appendSection("Decisions", items: summary.decisions.map(\.description), to: &lines)
        appendSection("Action Items", items: summary.actionItems.map(\.description), to: &lines)
        appendSection("Open Questions", items: summary.openQuestions, to: &lines)
        appendSection("Risks", items: summary.risks, to: &lines)
        appendSection("Follow Ups", items: summary.followUps, to: &lines)

        return lines.joined(separator: "\n") + "\n"
    }

    private static func appendTags(_ tags: [MeetingSummaryTag], to lines: inout [String]) {
        let visibleTags = tags.filter { !$0.label.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty }
        guard !visibleTags.isEmpty else { return }
        lines.append("## Tags")
        lines.append("")
        lines.append(contentsOf: visibleTags.map { tag in
            let percent = Int((tag.confidence * 100).rounded())
            let rationale = tag.rationale?.trimmingCharacters(in: .whitespacesAndNewlines)
            if let rationale, !rationale.isEmpty {
                return "- \(tag.label) (\(percent)%) - \(rationale)"
            }
            return "- \(tag.label) (\(percent)%)"
        })
        lines.append("")
    }

    private static func appendSection(_ title: String, items: [String], to lines: inout [String]) {
        let visibleItems = items
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
        guard !visibleItems.isEmpty else { return }
        lines.append("## \(title)")
        lines.append("")
        if visibleItems.count == 1, title == "Overview" {
            lines.append(visibleItems[0])
        } else {
            lines.append(contentsOf: visibleItems.map { "- \($0)" })
        }
        lines.append("")
    }
}

public enum MeetingSummaryWriter {
    public static func write(_ summary: MeetingSummary, jsonURL: URL, markdownURL: URL) throws {
        let data = try JSONEncoder.meetingAgent.encode(summary)
        try data.write(to: jsonURL, options: .atomic)
        try MeetingSummaryMarkdownRenderer.render(summary).write(to: markdownURL, atomically: true, encoding: .utf8)
    }

    public static func read(from url: URL) throws -> MeetingSummary {
        let data = try Data(contentsOf: url)
        return try JSONDecoder.meetingAgent.decode(MeetingSummary.self, from: data)
    }
}
