import Foundation

public struct OpenRouterMeetingSummaryProvider: MeetingSummaryProvider {
    public var providerName: String {
        switch configuration {
        case .available(_, let model):
            return "openrouter:\(model)"
        case .unavailable:
            return "openrouter"
        }
    }

    private let configuration: OpenRouterChatConfiguration
    private let client: OpenRouterChatClient

    public init(
        configuration: OpenRouterChatConfiguration = .environment(
            model: ProcessInfo.processInfo.environment["MEETING_AGENT_OPENROUTER_MODEL"]
        ),
        client: OpenRouterChatClient = URLSessionOpenRouterChatClient()
    ) {
        self.configuration = configuration
        self.client = client
    }

    public func generateSummary(input: MeetingSummaryInput) async throws -> MeetingSummary {
        let sourceSegmentIDs = input.segments
            .map(\.id)
        switch configuration {
        case .unavailable(let reason):
            return failedSummary(input: input, sourceSegmentIDs: sourceSegmentIDs, reason: reason)
        case .available:
            do {
                let content = try await client.complete(
                    configuration: configuration,
                    messages: Self.messages(for: input),
                    responseFormat: OpenRouterResponseFormat(type: "json_object")
                )
                let payload = try Self.decodePayload(from: content)
                let title = MeetingSummaryTitleGenerator.title(
                    meetingName: input.meetingName,
                    keyTopics: payload.keyTopics,
                    overview: payload.overview,
                    segments: input.segments
                )
                return MeetingSummary(
                    autoGeneratedTitle: MeetingSummaryTitleGenerator.title(
                        meetingName: payload.autoGeneratedTitle ?? "",
                        keyTopics: [],
                        overview: payload.autoGeneratedTitle ?? "",
                        segments: []
                    ) ?? title,
                    overview: payload.overview,
                    keyTopics: payload.keyTopics,
                    decisions: payload.decisions,
                    actionItems: payload.actionItems,
                    openQuestions: payload.openQuestions,
                    risks: payload.risks,
                    followUps: payload.followUps,
                    tags: payload.tags,
                    language: input.language ?? input.segments.compactMap(\.language).first,
                    sourceSegmentIDs: sourceSegmentIDs,
                    generatedAt: input.generatedAt,
                    provider: providerName,
                    status: .succeeded,
                    failureReason: nil
                )
            } catch {
                return failedSummary(
                    input: input,
                    sourceSegmentIDs: sourceSegmentIDs,
                    reason: "OpenRouter summary generation failed: \(error)"
                )
            }
        }
    }

    private static func messages(for input: MeetingSummaryInput) -> [OpenRouterChatMessage] {
        [
            OpenRouterChatMessage(role: "system", content: """
            You summarize business meetings for managers. Return only valid JSON with these keys: autoGeneratedTitle, overview, keyTopics, tags, decisions, actionItems, openQuestions, risks, followUps. autoGeneratedTitle must be a concise natural meeting title, not the application or browser name. tags must contain 2-4 freeform insight tags that help a manager understand and later find the meeting; each tag must contain label, rationale, confidence, sourceSegmentIDs. Tags may mix meeting type, topic, outcome clarity, risk, dependency, decision stage, or another useful dimension chosen from the transcript. decisions must contain description, participants, sourceSegmentIDs, confidence. actionItems must contain description, owner, dueDate, sourceSegmentIDs, confidence.
            """),
            OpenRouterChatMessage(role: "user", content: prompt(for: input))
        ]
    }

    private static func prompt(for input: MeetingSummaryInput) -> String {
        var lines = [
            "Meeting name: \(input.meetingName)",
            "Transcript language: \(input.language ?? "unknown")",
            "Summary target language: \(input.targetLanguage ?? input.language ?? "unknown")",
            "Write every generated JSON string value in the summary target language."
        ]
        if let meetingGoal = input.meetingGoal?.trimmingCharacters(in: .whitespacesAndNewlines),
           !meetingGoal.isEmpty {
            lines.append("Meeting goal: \(meetingGoal)")
        }
        lines.append("")
        lines.append("Transcript segments:")
        lines.append(contentsOf: input.segments.map { segment in
            let speaker = segment.speakerLabel ?? segment.speakerID ?? "Unknown speaker"
            return "- id: \(segment.id)\n  speaker: \(speaker)\n  text: \(segment.text)"
        })
        return lines.joined(separator: "\n")
    }

    private static func decodePayload(from content: String) throws -> OpenRouterSummaryPayload {
        let trimmed = content.trimmingCharacters(in: .whitespacesAndNewlines)
        let json = try extractJSONObject(from: trimmed)
        return try JSONDecoder.meetingAgent.decode(OpenRouterSummaryPayload.self, from: Data(json.utf8))
    }

    private static func extractJSONObject(from content: String) throws -> String {
        guard let start = content.firstIndex(of: "{"),
              let end = content.lastIndex(of: "}"),
              start <= end
        else {
            throw OpenRouterChatError.invalidJSONContent
        }
        return String(content[start...end])
    }

    private func failedSummary(input: MeetingSummaryInput, sourceSegmentIDs: [String], reason: String) -> MeetingSummary {
        MeetingSummary(
            autoGeneratedTitle: nil,
            overview: "",
            keyTopics: [],
            decisions: [],
            actionItems: [],
            openQuestions: [],
            risks: [],
            followUps: [],
            tags: [],
            language: input.language,
            sourceSegmentIDs: sourceSegmentIDs,
            generatedAt: input.generatedAt,
            provider: providerName,
            status: .failed,
            failureReason: reason
        )
    }
}

private struct OpenRouterSummaryPayload: Decodable {
    let autoGeneratedTitle: String?
    let overview: String
    let keyTopics: [String]
    let tags: [MeetingSummaryTag]
    let decisions: [MeetingDecision]
    let actionItems: [MeetingActionItem]
    let openQuestions: [String]
    let risks: [String]
    let followUps: [String]

    private enum CodingKeys: String, CodingKey {
        case autoGeneratedTitle
        case overview
        case keyTopics
        case tags
        case decisions
        case actionItems
        case openQuestions
        case risks
        case followUps
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        autoGeneratedTitle = try container.decodeIfPresent(String.self, forKey: .autoGeneratedTitle)
        overview = try container.decode(String.self, forKey: .overview)
        keyTopics = try container.decode([String].self, forKey: .keyTopics)
        tags = try container.decodeIfPresent([MeetingSummaryTag].self, forKey: .tags) ?? []
        decisions = try container.decode([MeetingDecision].self, forKey: .decisions)
        actionItems = try container.decode([MeetingActionItem].self, forKey: .actionItems)
        openQuestions = try container.decode([String].self, forKey: .openQuestions)
        risks = try container.decode([String].self, forKey: .risks)
        followUps = try container.decode([String].self, forKey: .followUps)
    }
}
